### ISSUE TITLE
Could we remove this please.

### ISSUE THREAD

**Issue by sbarow** [ghanemabdo/FlickerImages#1]
https://github.com/ghanemabdo/FlickerImages/blob/6f346dc5ea56f7e6f6bb6f588f638a7f80d3c85f/FlickerImages/Model/JSONNetworkOperation.swift#L31

**Comment by ghanemabdo** [comment]
Done. Replaced and file renamed to IndexNetworkOperation.swift. Also check the comment in the code. Please pull the last commit
